### ISSUE TITLE
PBR ETK Driving Center

### ISSUE THREAD

**Issue by JonLit** [SnoutBug/BeamNG_terrainMaterialCache#1]
At least for me, the new ETK Driving Center also has Black Textures.

**Comment by SnoutBug** [comment]
yes, Bauer33333 contacted me about this already. If everything works out a new release should be published soon containing textures for all recently reworked maps

**Comment by SnoutBug** [comment]
```Bash
mkdir ~/.steam/root/steamapps/compatdata/284160/pfx/drive_c/users/steamuser/AppData/Local/BeamNG.drive/0.24/temp/art
cd "$_"
url=github.com/SnoutBug/BeamNG_terrainMaterialCache/releases/download/default/
wget ${url}etk.tar.gz
wget ${url}jri.tar.gz
wget ${url}utah.tar.gz
wget ${url}derby.tar.gz
wget ${url}hirochi.tar.gz
wget ${url}industrial.tar.gz
wget ${url}gridmap_v2.tar.gz
wget ${url}small_island.tar.gz
ls *.tar.gz | xargs -n 1 tar -xvf
rm *.tar.gz
cd ~/
```
This should get you all necessary textures. I wasn't able to test this though since I don't have access to my computer at this moment.
Feel free to re-open this issue if the textures remain black.
