### ISSUE TITLE
v0.25 PBR

### ISSUE THREAD

**Issue by WhiteHusky** [SnoutBug/BeamNG_terrainMaterialCache#10]
https://mega.nz/file/EKxCRbDD#WafDtqm4VG1u8YsuMpOT7YRV9h_wWiH0-kq_CT3qyoc
Right on the tin.

For anyone else waiting for the repo owner to update the files:
 * Download this archive
 * Bring yourself to:
`
~/.steam/root/steamapps/compatdata/284160/pfx/drive_c/users/steamuser/AppData/Local/BeamNG.drive/0.25/temp/art
`
Mind, this is for Steam installs. For WINE, defer to where you made your prefix and work from there.
 * Create a `terrainMaterialCache` folder
 * Collect all the `.dds` files from the archive and put them in the created folder
   * If this is too tedious, consider the following command:
     `find $extractedArchiveLocation -execdir mv {} $terrianMaterialCacheLocation \;`
     Mind, this is `mv` so use `cp` if you don't want to move the files but instead copy them.

**Comment by WhiteHusky** [comment]
Oop. Forgot to upload the files. Wait a moment...

**Comment by WhiteHusky** [comment]
Link added to issue.

**Comment by WhiteHusky** [comment]
This issue is related to #9

**Comment by SnoutBug** [comment]
I will add the new files later today.
