### ISSUE TITLE
0.26 Update

### ISSUE THREAD

**Issue by JonLit** [SnoutBug/BeamNG_terrainMaterialCache#13]
The Instructions aren't updated to work with 0.26 (-> fixed)

**Comment by JonLit** [comment]
nevermind, I think it's generally not working anymore, OGC also told me that the Textures had been renamed, that might be the issue. I think the easiest "fix" might be to re-generate all the Textures on a Windows machine/ the native BeamNG port.

**Comment by SnoutBug** [comment]
> I think the easiest "fix" might be to re-generate all the Textures on a Windows machine/ the native BeamNG port.

yes I agree, I will close this once we're done collecting all the latest textures

**Comment by SnoutBug** [comment]
might be no longer necessary: https://github.com/ValveSoftware/wine/pull/160, I will check if this works once I'm home if nobody leapfrogs me 
**Edit: yes, proton experimental bleeding edge fixes this**

**Comment by snakeeater4526** [comment]
can confirm it doesn't work anymore, something related to an error 404 not found? ( cry in black texture lol )

vk build isn't helping me with steam deck ( crash when loading map )

and currently neither proton experimental nor proton GE fix this  ( though from what i've seen i need to wait the next release of proton experimental for that )

**Comment by SnoutBug** [comment]
> can confirm it doesn't work anymore, something related to an error 404 not found? ( cry in black texture lol )

might be a github issue, I just checked and the script worked fine.

> and currently neither proton experimental nor proton GE fix this

did you [enable bleeding edge](https://github.com/SnoutBug/BeamNG_terrainMaterialCache/blob/main/switch.md)?

**Comment by snakeeater4526** [comment]
Just enabled bleeding edge, thanks now it work ( though it needed a reinstall to reset cache since you can't easily reset it on steam deck)

Now 2 problem, but I thinks it's more beamNG itself related, 1. texture ( especially road ) have square artefact and it's getting worse and Worse with resolution down sampling.
2. The game eat a freaking amount of ram and might crash sometimes , currently use 12.5go ram and 4.4 VRAM ( steam deck use 16gb DDR5... Well...) 

Again thanks a freaking lot 🙏

**Comment by JonLit** [comment]
> Just enabled bleeding edge, thanks now it work ( though it needed a reinstall to reset cache since you can't easily reset it on steam deck)
> 
> Now 2 problem, but I thinks it's more beamNG itself related, 1. texture ( especially road ) have square artefact and it's getting worse and Worse with resolution down sampling. 2. The game eat a freaking amount of ram and might crash sometimes , currently use 12.5go ram and 4.4 VRAM ( steam deck use 16gb DDR5... Well...)
> 
> Again thanks a freaking lot pray

Other users have reported similar problems on the linux port feedback thread on the beamng forums.
The artifacts occur for me, too :(

**Comment by ThatCoolCoder** [comment]
Like snakeeater4526, I was having problems getting bleeding edge to work. I found that also on PC you need to clear the Steam cache then completely reinstall proton experimental.

**Comment by stefo-beam2drive** [comment]
I checked my maps. Italy and West Coast don't have textures, at least for me they don't.
