### ISSUE TITLE
vanilla maps re-generated

### ISSUE THREAD

**Issue by JonLit** [SnoutBug/BeamNG_terrainMaterialCache#14]
**Mod name**
vanilla Maps

**URL on Website**
www.beamng.com/

**URL to archive with cached files**
https://we.tl/t-U099gCu0PB

**Comment by raspimana** [comment]
Here's a google drive link if anyone needs it when the wetransfer link expires: https://drive.google.com/file/d/1K3N13wUjnRoJDfOOKFmm7bBKTsZBSDOP/view

**Comment by schrammalama** [comment]
How do I install this?

**Comment by JonLit** [comment]
> How do I install this?

download all the .zip files, and extract them to `~/.steam/root/steamapps/compatdata/284160/pfx/drive_c/users/steamuser/AppData/Local/BeamNG.drive/0.26/temp/art/terrainMaterialCache`
In this folder there should be ~700MB (maybe more) of .dds files after you're done.
should look like this (path may depend on your username / install location of BeamNG)
![image](https://user-images.githubusercontent.com/55829273/191315587-03a1e26f-b07b-420b-a314-232e77751097.png)


If you're using BeamNG with wine, it should look like this (exchange the path with the corresponding path to your wine prefix):
![image](https://user-images.githubusercontent.com/55829273/191315454-53138e96-349f-4cdf-9853-01d5b0603abf.png)

**Comment by SnoutBug** [comment]
Thank you, I added the files!
