### ISSUE TITLE
Black textures in Italy and West Coast

### ISSUE THREAD

**Issue by stefo-beam2drive** [SnoutBug/BeamNG_terrainMaterialCache#15]
Hi,

I'm sorry if I just installed something wrong. I reinstalled the textures 3 times.
But they were black in WC and Italy, can someone help me?

**Comment by SnoutBug** [comment]
@stefo-beam2drive It is possible that there are files in your `terrainMaterialCache` folder with different capitalization. 

Try completely clearing the folder and rerunning the script. 

If that still does not work you can try to generate your own textures with
```Bash
curl https://raw.githubusercontent.com/SnoutBug/BeamNG_terrainMaterialCache/main/generate_textures.py | python3 - west_coast_usa
```
and 
```Bash
curl https://raw.githubusercontent.com/SnoutBug/BeamNG_terrainMaterialCache/main/generate_textures.py | python3 - italy
```

**Comment by stefo-beam2drive** [comment]
I just tried that in West Coast, but I got the error: "Non-Steam is not supported right now..."

Here's a picture:

[](url)
<img width="576" alt="Bildschirmfoto 2022-10-09 um 15 27 31" src="https://user-images.githubusercontent.com/114953834/194759573-9bc512d8-70a6-47d0-90bd-380dea95b36b.png">

**Comment by stefo-beam2drive** [comment]
I just fixed the maps!!!
I took the textures here: 
https://github.com/SnoutBug/BeamNG_terrainMaterialCache/issues/14
put them into the art folder, and they work!!
