### ISSUE TITLE
Repository-PBR-Textures - East Coast snowing

### ISSUE THREAD

**Issue by kevenwyld** [SnoutBug/BeamNG_terrainMaterialCache#16]
**Mod name**
ecusa_snowing (East Coast snowing)

**URL on Website**
www.beamng.com/resources/east-coast-snowing.24052/

**URL to archive with cached files**
https://filebin.net/otsijxl6k3wc4w1u (updated, I messed up the first one)

FFB doesn't work in experimental yet and I like this map =]

Thanks!

**Comment by kevenwyld** [comment]
I updated the link.  I messed up and didn't include some files in the first one.

**Comment by SnoutBug** [comment]
Thank you, I've created a new release!
