### ISSUE TITLE
"Non steam isn't supported right now" even though I am using steam

### ISSUE THREAD

**Issue by chair-man-f** [SnoutBug/BeamNG_terrainMaterialCache#21]
Steam, using Porting Kit

command: 
MAP="italy" && curl https://raw.githubusercontent.com/SnoutBug/BeamNG_terrainMaterialCache/main/generate_textures.py | python3 - $MAP

I want to generate textures for mods and Automation test track by myself so I hope this gets fixed

**Comment by SnoutBug** [comment]
can you confirm if steam exists at either
`~/.var/app/com.valvesoftware.Steam/.steam/root/` or `~/.steam/root/`
and if not, where is your steam located?

**Comment by chair-man-f** [comment]
<img width="1051" alt="Screenshot 2023-11-19 at 17 13 26" src="https://github.com/SnoutBug/BeamNG_terrainMaterialCache/assets/117324349/71fa74e1-01cd-4e79-b9de-a25a79bedc72">
steam is here
<img width="515" alt="Screenshot 2023-11-19 at 17 13 56" src="https://github.com/SnoutBug/BeamNG_terrainMaterialCache/assets/117324349/b8257afd-6bfc-4f70-873a-2c3edd93b043">
which is in this app

**Comment by chair-man-f** [comment]
oh shit I didn't read that this is only for Linux 

is it possible to generate my own textures on mac?

**Comment by SnoutBug** [comment]
from the looks of it you are using a mac? The script is only supported on linux

**Comment by chair-man-f** [comment]
<img width="1015" alt="Screenshot 2023-11-21 at 19 00 12" src="https://github.com/SnoutBug/BeamNG_terrainMaterialCache/assets/117324349/2631c32f-368b-46cc-868d-33e8e48a3cfb">
oh it looked like it was under running the game with crossover to me sorry


but is there a way to generate my own textures?

**Comment by SnoutBug** [comment]
No worries, I added an extra line to clarify just now.

`but is there a way to generate my own textures?`
I think you might be out of luck. The script relies on the native binary of BeamNG.drive for Linux to genereate the textures. Meaning for the automated script to work you would have to get the linux version running, by using a virtual machine or dual booting. But that is probably more hassle than it's worth.
You may also try to contact the cross over developers about this issue. Valve was really quick to respond back in the days and fixed the texture issue for proton.

**Comment by chair-man-f** [comment]
yEah I remember playing on Parallels before game porting toolkit officially came out and the textures were fine, but the performance was absolute garbage so I couldn't play on it, so I'm considering generating textures there and copying them but yeah probably not worth the hassle
