### ISSUE TITLE
Repository-PBR-Textures (Natural Playground 1.0.1)

### ISSUE THREAD

**Issue by ghost** [SnoutBug/BeamNG_terrainMaterialCache#3]
**Mod name**
Natural Playground 1.0.1

**URL on Website**
https://www.beamng.com/resources/natural-playground.18030/

http://lloydlynx.ddns.net/ext/terrainMaterialCache/terrainMaterialCacheNaturalPlayground1.0.1.zip

**Comment by SnoutBug** [comment]
[Release already exists](https://github.com/SnoutBug/BeamNG_terrainMaterialCache/releases/tag/18030)
