### ISSUE TITLE
Repository-PBR-Textures (Motorsports Playground)

### ISSUE THREAD

**Issue by JonLit** [SnoutBug/BeamNG_terrainMaterialCache#4]
**Mod name**
Motorsports Playground

**URL on Website**
[www.beamng.com/resources/](https://www.beamng.com/resources/motorsports-playground.21834/)

**URL to archive with cached files**
https://mega.nz/file/YFt0AKKQ#0610bvigvl4MNdX0Fv3I2nPZzhNvhyuYkjx1lQ3MbfI

P.S.
GitHub File Upload would be really nice instead of relying on third-party cloud services (so that I could upload the .zip File directly attached to this "issue")

**Comment by SnoutBug** [comment]
> GitHub File Upload would be really nice instead of relying on third-party cloud services (so that I could upload the .zip File directly attached to this "issue")

Unfortunately GitHub only allows filesizes up to 25MB

There is probably a nicer way of doing this by utilizing pull requests and storing the textures inside the repo itself rather than the releases.

I've added a new release. Thank you!

**Comment by JonLit** [comment]
Hi, I think the textures are outdated, I repeated the process, here are the new ones
[https://mega.nz/file/ENkXADwR#HBnrfBMW9XNLAxSSIDnXAtKRAn_SkKP_oQhqg4A2W9s](https://mega.nz/file/ENkXADwR#HBnrfBMW9XNLAxSSIDnXAtKRAn_SkKP_oQhqg4A2W9s)

**Comment by SnoutBug** [comment]
Thanks, i've updated the release
