### ISSUE TITLE
Repository-PBR-Textures (Utah Extra 4.0)

### ISSUE THREAD

**Issue by SuntyX** [SnoutBug/BeamNG_terrainMaterialCache#6]
**Mod name**
The name of the mod is Utah Extra

**URL on Website**
www.beamng.com/resources/utah-extra.18058

**URL to archive with cached files**
https://www.mediafire.com/file/cmfoqeonadwyimy/78B558B2EB821D18.zip/file

**Comment by SnoutBug** [comment]
Thank you, I've added a new release!
