### ISSUE TITLE
Script Error: KeyError: 'modData'

### ISSUE THREAD

**Issue by JonLit** [SnoutBug/BeamNG_terrainMaterialCache#7]
Hi,
tried using the script, but I only get this output (removing the three `['modData']` skips the search for modded maps, but then "works"):
```
    curl https://raw.githubusercontent.com/SnoutBug/BeamNG_terrainMaterialCache/main/auto_update.py | python3 -
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  3997  100  3997    0     0  49985      0 --:--:-- --:--:-- --:--:-- 50594


Starting to update.
You can always cancel the download by pressing CTRL + C

Looking for modded maps...
Traceback (most recent call last):
File "<stdin>", line 60, in <module>
KeyError: 'modData'
```

**Comment by SnoutBug** [comment]
Weird, does the file `db.json` in `/.steam/root/steamapps/compatdata/284160/pfx/drive_c/users/steamuser/AppData/Local/BeamNG.drive/0.24/mods/` exist?
 
Edit: I guess it has to exist, can you send me the contents of the mentioned file?

**Comment by JonLit** [comment]
[db.txt](https://github.com/SnoutBug/BeamNG_terrainMaterialCache/files/8747636/db.txt)
(had to rename it into a .txt else it won't upload)

**Comment by SnoutBug** [comment]
Thanks! Should work now

**Comment by JonLit** [comment]
indeed, thanks!
