### ISSUE TITLE
OGC Map

### ISSUE THREAD

**Issue by JonLit** [SnoutBug/BeamNG_terrainMaterialCache#8]
**Mod name**
OGC Map - Ultimate Beam.NG Map
Update 0.21

**URL on Website**
[www.beamng.com/resources/](https://beamng.com/resources/ogc-map-ultimate-beam-ng-map.22814/)

**URL to archive with cached files**
https://ufile.io/ymals82v (will expire in 30 days, on July 9th)

**Comment by SnoutBug** [comment]
Thank you, I've a new release! :)
